---
- include_tasks: install/debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker
  package:
    name: "docker-{{ docker_edition }}"
    state: present
  notify: restart docker

- name: Initializing Swarm
  include_tasks: swarm/leader.yml
  include_tasks: swarm/worker.yml
  when: swarm_mode is defined
